travis:
  secure:
    BINSTAR_TOKEN: YhxQZNuZUz0Yejj5W7hrkHwiZ+6d2AKWazzQJ4rH6q5AmEeY1UKObPHCao9OS4fmTfQUaCIe1rPyicKvZymrEHSfraR882KZKClhBZ92AR0hBokie7D0W4H2ZMUfoxnhtuzN/hOjVqZG6AOvCRe7hcStGzZLjIjtxOO+2T4uv6gEDtI0JyKHBpz1ZORpZuTfp7TEYauOhuLvtKvKYoxhU56M3dzTfYn+Wo0BDolanHAVJ1Hi57+hMmd8CG+3qVLyGrei+3pTa8RjNacgpFpti0C8Tf8UhhqyXeY8968mDUbkr/VA3hR3ueKeviMDUEnxSWaG5JMpFDzKrdOStOR9sezXFMUwbCCGeM821EY4XKx2/JRn6iFfSkG3PV5j5qmvt930JyE0gg8Sol6ID/Lw1Fl9kZKKr8NP2v+oq01iwP//xLu91xQY4mCsRwqSYjHWrOvyCRD0UY7zJfGZuimFAMZBMebNTN7PR+SDud/ehwE8NJd5LKaBP/wsS6wuRyKEFAigx7Vk6oSrtqB1tM4ffv0eJewzxj18bv5Ny5sILge3ak4jv4ut3aLr4zlJDMei8ibZ3J/0WbVq7WV5iDECo2tG5DOrZgQQmd4SUvAVRNSlOwtBYVn99xTpwyi6YQUdAj3KKVFVcUvDrZwOi6vSeSjt5boObfGw3cJu0SFesZ4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
